
export const MentionsActionTypes = {

    MENTIONS_LOADING : "MENTIONS_LOADING",
    MENTIONS_LOADED  : "MENTIONS_LOADED",
    MENTIONS_ERROR   : "MENTIONS_ERROR",

    SAVE_ANS_LOADING : "SAVE_ANS_LOADING",
    SAVE_ANS_LOADED  : "SAVE_ANS_LOADED",
    SAVE_ANS_ERROR   : "SAVE_ANS_ERROR",

    GET_ANS_LOADING : "GET_ANS_LOADING",
    GET_ANS_LOADED  : "GET_ANS_LOADED",
    GET_ANS_ERROR   : "GET_ANS_ERROR"

}