
export const MentionsActionTypes = {

    MENTIONS_LOADING : "MENTIONS_LOADING",
    MENTIONS_LOADED  : "MENTIONS_LOADED",
    MENTIONS_ERROR   : "MENTIONS_ERROR",

    // USERS_LOADING : "USERS_LOADING",
    // USERS_LOADED  : "USERS_LOADED",
    // USERS_ERROR   : "USERS_ERROR",

    // SAVE_ANS_LOADING : "SAVE_ANS_LOADING",
    SAVE_ANS_LOADED  : "SAVE_ANS_LOADED",
    // SAVE_ANS_ERROR   : "SAVE_ANS_ERROR" 

}