
export const PageAccessActionTypes = {

    PAGE_ROLE_LOADING : "PAGE_ROLE_LOADING",
    PAGE_ROLE_LOADED  : "PAGE_ROLE_LOADED",
    PAGE_ROLE_ERROR   : "PAGE_ROLE_ERROR",

    USER_LIST_LOADING : "USER_LIST_LOADING",
    USER_LIST_LOADED  : "USER_LIST_LOADED",
    USER_LIST_ERROR   : "USER_LIST_ERROR",

    ACCESS_REQ_LOADING : "ACCESS_REQ_LOADING",
    ACCESS_REQ_LOADED  : "ACCESS_REQ_LOADED",
    ACCESS_REQ_ERROR   : "ACCESS_REQ_ERROR"

}