export const followQuestionsActionTypes = {
    
    FLLW_QUES_LOADING: "FLLW_QUES_LOADING",
    FLLW_QUES_LOADED: "FLLW_QUES_LOADED",
    FLLW_QUES_LOADING_MORE: "FLLW_QUES_LOADING_MORE",
    FLLW_QUES_MORE_LOADED: "FLLW_QUES_MORE_LOADED",
    FLLW_QUES_ERRORS: "FLLW_QUES_ERRORS"
}

