
export const pendingInvitationActionTypes = {

    PND_INV_LOADING:        "PND_INV_LOADING",
    PND_INV_LOADED:         "PND_INV_LOADED",
    PND_INV_MORE_LOADING:   "PND_INV_MORE_LOADING",
    PND_INV_MORE_LOADED:    "PND_INV_MORE_LOADED",

    PND_INV_ACCEPT_LOADING: "PND_INV_ACCEPT_LOADING",
    PND_INV_ACCEPT_LOADED:  "PND_INV_ACCEPT_LOADED",
    PND_INV_DELETE_LOADING: "PND_INV_DELETE_LOADING",
    PND_INV_DELETE_LOADED:  "PND_INV_DELETE_LOADED"

}