
export const ApproveRolesActionTypes = {

    ROLE_REQ_LOADING        : "ROLE_REQ_LOADING",
    ROLE_REQ_LOADED         : "ROLE_REQ_LOADED",
    ROLE_REQ_MORE_LOADING   : "ROLE_REQ_MORE_LOADING",
    ROLE_REQ_MORE_LOADED    : "ROLE_REQ_MORE_LOADED",

    ROLE_REQ_ACCEPT_LOADING : "ROLE_REQ_ACCEPT_LOADING",
    ROLE_REQ_ACCEPT_LOADED  : "ROLE_REQ_ACCEPT_LOADED",
    ROLE_REQ_REJECT_LOADING : "ROLE_REQ_REJECT_LOADING",
    ROLE_REQ_REJECT_LOADED  : "ROLE_REQ_REJECT_LOADED",

    ROLE_REQ_ERROR          : "ROLE_REQ_ERROR"
}