export const savedQuestionsActionTypes = {
    
    SAVED_QUES_LOADING: "SAVED_QUES_LOADING",
    SAVED_QUES_LOADED: "SAVED_QUES_LOADED",
    
    SAVED_QUES_LOADING_MORE: "SAVED_QUES_LOADING_MORE",
    SAVED_QUES_MORE_LOADED: "SAVED_QUES_MORE_LOADED",

    SAVED_QUES_ERRORS: "SAVED_QUES_ERRORS"

}