export const accountSettingsActionTypes = {
    ACC_SETTING_USER_DETAILS_LOADING: "ACC_SETTING_USER_DETAILS_LOADING",
    ACC_SETTING_USER_DETAILS_LOADED: "ACC_SETTING_USER_DETAILS_LOADED",
    ACC_SETTING_ERRORS: "ACC_SETTING_ERRORS"
}