
export const ApplicationsActionTypes = {

    APPLICATIONS_LOADING:      "APPLICATIONS_LOADING",
    APPLICATIONS_LOADED:       "APPLICATIONS_LOADED",
    APPLICATIONS_LOADING_MORE: "APPLICATIONS_LOADING_MORE",
    APPLICATIONS_MORE_LOADED:  "APPLICATIONS_MORE_LOADED",
    APPLICATIONS_ERROR:        "APPLICATIONS_ERROR"

}